name: Purnama
description: "Proyek Flutter Reservasi Hotel & Restoran Purnama Balige."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- STATE MANAGEMENT ---
  provider: ^6.1.2

  # --- FITUR PERANGKAT & HAPTIC ---
  vibration: ^3.1.8              # Untuk efek getar HP saat Caution/Error

  
  # --- FORM INPUT & VALIDASI MODERN ---
  pinput: ^5.0.0                 # Untuk input OTP kotak-kotak premium
  intl_phone_field: ^3.2.0       # Untuk input No HP + Search negara (+62)
  image_picker: ^1.1.0           # Untuk ambil foto profil dari galeri

  # --- UI & IKON ---
  cupertino_icons: ^1.0.8

  # --- JARINGAN & API ---
  http: ^1.2.1                   # Untuk koneksi ke Mikroservis (8000, 8001, 8002)

  # --- PENYIMPANAN LOKAL (SESSION) ---
  shared_preferences: ^2.2.3      # Untuk simpan Token, Nama, & Status Guest

  # --- UTILITAS DATA ---
  intl: ^0.19.0                  # Untuk format Mata Uang (Rp) dan Tanggal

  # --- PEMBAYARAN & WEB (MIDTRANS) ---
  webview_flutter: ^4.7.0        # Untuk menampilkan layar bayar Midtrans Snap
  url_launcher: ^6.2.5           # Untuk membuka link eksternal browser

  # --- NOTIFIKASI & FIREBASE ---
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.1
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # Library untuk generate ikon aplikasi otomatis
  flutter_launcher_icons: ^0.13.1

# --- KONFIGURASI GENERATE IKON APLIKASI ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon_purnama.png"
  min_sdk_android: 21 

# --- PENGATURAN ASSETS ---
flutter:
  uses-material-design: true

  assets:
    - assets/images/             # Folder untuk logo & banner promo
    - assets/icons/              # Folder untuk icon_purnama.pngf