name: Purnama
description: "Proyek Flutter Reservasi Hotel & Restoran Purnama Balige."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # STATE MANAGEMENT
  provider: ^6.1.5+1

  # FITUR PERANGKAT & HAPTIC
  vibration: ^3.1.8

  # FORM INPUT & VALIDASI MODERN
  pinput: ^5.0.0
  intl_phone_field: ^3.2.0
  image_picker: ^1.2.1

  # UI & IKON
  cupertino_icons: ^1.0.8

  # JARINGAN & API
  http: ^1.6.0

  # PENYIMPANAN LOKAL (SESSION)
  shared_preferences: ^2.5.4

  # UTILITAS DATA
  intl: ^0.19.0

  # PEMBAYARAN & WEB
  webview_flutter: ^4.7.0
  url_launcher: ^6.3.2
  midtrans_snap: ^1.0.1

  # NOTIFIKASI & FIREBASE
  firebase_core: ^4.7.0
  firebase_messaging: ^16.2.0
  flutter_local_notifications: ^17.0.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

# KONFIGURASI GENERATE IKON APLIKASI
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon_purnama.png"
  min_sdk_android: 21

# PENGATURAN ASSETS
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/